import { GOAL_CAM_FAR, GOAL_CAM_FOV, GOAL_CAM_NEAR } from './camera'

export const HERO_WIDE_RADIUS = 3.2
export const HERO_WIDE_HEIGHT = 2.5
export const HERO_ORBIT_SPEED = 0.12
export const HERO_WIDE_DURATION = 14
export const HERO_PLAYER_DURATION = 10
export const HERO_TRANSITION_DURATION = 2

export const HERO_CYCLE_DURATION =
  HERO_WIDE_DURATION +
  HERO_TRANSITION_DURATION +
  HERO_PLAYER_DURATION +
  HERO_TRANSITION_DURATION

export const HERO_CAM_FOV = GOAL_CAM_FOV
export const HERO_CAM_NEAR = GOAL_CAM_NEAR
export const HERO_CAM_FAR = GOAL_CAM_FAR
